name: pet_trainer_frontend
description: Pet Trainer Flutter Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Added dependencies
  http: ^1.1.0
  provider: ^6.0.5
  camera: ^0.10.5
  web_socket_channel: ^2.4.0
  fl_chart: ^0.66.0

  cupertino_icons: ^1.0.2
  image: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/characters/
    - assets/images/
    - assets/data/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon2.png" # 아이콘 파일 경로
  # 안드로이드 8.0 이상을 위한 Adaptive Icon 설정 (선택사항)
  adaptive_icon_background: "#ffffff" # 배경색
#   adaptive_icon_foreground: "assets/images/icon_foreground.png" # 전경 이미지